[build]
  command = "npm ci && ./node_modules/.bin/vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
